### PR TITLE
Add airflow documentation and implementation

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This adds the proposal and proposal implementation for running Prio in Airflow.

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
@wlach feedback on `docs/scheduler.md` before I spend 1-2 days on implementation. I think airflow is a good choice because it already handles connections (role based authentication, password management), has a nice high level interface for constructing DAGs, and operators that work with the stack that we've considered i.e. s3/gcs and docker.

**Comment by wlach** [comment]
@acmiyaguchi I still think airflow is overkill for this stage of the project. It's going to create a whole set of complexity around build and deployment that is not necessary at this point: it is not clear to me that we need password validation or role-based authentication for the MVP to be workable. Can we just get something running that does the absolute bare minimum? We can always add complexity and features later.

**Comment by acmiyaguchi** [comment]
@wlach Sure, I can think of something simpler while maintaining minimal operational overhead. I'll shelve this for later after implementing something smaller in scope with a different triggering mechanism.

**Comment by acmiyaguchi** [comment]
This is going to be implemented in mozilla/telemetry-airflow instead. Most of the workflow components have been baked directly into the container.

**Pull request closed without merging**
